apiVersion: v1
kind: Pod
metadata:
  name: lab5-pod
spec:
  volumes:
    - name: shared-data
      emptyDir: {}
  initContainers:
    - name: init-mydata
      image: busybox:latest
      command: ["sh", "-c", "echo 'Hello from Init Container' > /data/index.html"]
      volumeMounts:
        - name: shared-data
          mountPath: /data
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html