apiVersion: v1
kind: Pod
metadata:
  name: lab-pod 
spec:
  volumes:
    - name: shared-data
      emptyDir: {}

  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html

    - name: busybox
      image: busybox:latest
      volumeMounts: 
        - name: shared-data
          mountPath: /data
      command: [ "sh", "-c","echo 'bsm allah' > /data/index.html; sleep 3600"]